### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by RobDangerous** [Kha-Samples/BulletTest#1]
Trying to run it in Kode Studio via the js code, it bails out complaining about a missing btDynamicsWorld constructor (cannot construct a btDynamicsWorld, no constructor in IDL). Help me @luboslenco. You're my only hope.

**Comment by RobDangerous** [comment]
Wait a minute, there's some old haxebullet repo lingering around and I'm accidentally using some old code...

**Comment by RobDangerous** [comment]
Didn't help much, similar error: "Ammo.btDefaultCollisionConfiguration is not a constructor". Do I maybe need to initialize the world differently?

**Comment by luboslenco** [comment]
Is the `haxe.macro.Compiler.includeFile("../Libraries/Bullet/js/ammo/ammo.js");` thingy working properly? I am not sure but recall having some trouble there.

I ended up loading `ammo.js` in a bit uglier way. I embed it as a blob asset and then do this monstrosity:

```hx
 kha.LoaderImpl.loadBlobFromDescription({ files: ["ammo.js"] }, function(b:kha.Blob) {
        var print = function(s:String) { trace(s); };
        var loaded = function() { print("ammo ready"); };
        untyped __js__("(1, eval)({0})", b.toString());
        untyped __js__("Ammo({print:print}).then(loaded)");
});
```

The `{print:print}` is to make it also run in Krom.

**Comment by RobDangerous** [comment]
The generated code looked fine to me (it just put ammo.js on top) but I now tried your method and now I'm back to "cannot construct a btDynamicsWorld, no constructor in IDL".

**Comment by RobDangerous** [comment]
Aha, I got something working. I still can't create a BtDynamicsWorld but a BtDiscreteDynamicsWorld works. And judging from the js code you really aren't supposed to create a BtDynamicsWorld, so the bindings should disallow that I guess.

**Comment by luboslenco** [comment]
This edit seems to work for me:
```haxe
//dynamicsWorld = new BtDynamicsWorld(dispatcher, broadphase, solver, collisionConfiguration);
dynamicsWorld = new BtDiscreteDynamicsWorld(dispatcher, broadphase, solver, collisionConfiguration);
```
Edit: Too late!

**Comment by RobDangerous** [comment]
Okidoki, all good.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/haxebullet/commit/80b9c115540bee344614bd0b1039bf45840c84db, will now throw
`haxebullet.BtDynamicsWorld does not have a constructor`.
